quarkus:
  config:
    profile:
      parent: common

"%common":
  quarkus:
    resteasy:
      gzip:
        enabled: true
    log:
      level: INFO
    http:
      root-path: <%= rootPath %>
      access-log:
        enabled: true
        exclude-pattern: long
  datasources:
    local:
      url: "https://example.com"
      user: "username"
      password: "password"